---
#- name: Clean Disks
#  command: "dd if=/dev/zero of=/dev/{{ loop_host_disk }} {{ dd_syntax }}"
#  async: "{{ dd_jobs_timeout }}"
#  poll: 0
#  loop: "{{ host_disk }}"
#  loop_control:
#    loop_var: loop_host_disk
#  register: dd_async

- name: execute job
  shell:
    "/tmp/clean-disks.sh {{ host_disk | to_yaml | replace('\n', '') }}"
  register: dd_async
  async: 3600
  poll:  0

- name: Check on DD status - Warning - can take a long time
  async_status:
    jid: "{{ dd_async.ansible_job_id }}"
  register: dd_async_job_result
  until: dd_async_job_result.finished
  retries: 3600
  delay: 60

