---
# tasks file for clean-disks

- name: copy script..
  template:
    src: "clean-disks.j2"
    dest: "/tmp/clean-disks.sh"

- name: fix perms..
  file:
    path: /tmp/clean-disks.sh
    mode: 0755

- name: Pre-condition disks Loop
  include: clean-disks.yaml
  with_sequence: count={{ dd_loop_count }}

- name: Delete test script
  file:
    path: /tmp/clean-disks.sh
    state: absent

