---
# tasks file for clean-disks

- name: setup
  set_fact:
    host_disk: []

- name: Get a list of block devices (excludes loop and child devices)
  command: lsblk -n --output NAME --nodeps --exclude 7
  register: lsblk_out

- name: check if disk is free - ERROR expected - don't panic
  command: pvcreate --test /dev/{{ item }}
  ignore_errors: true
  register: pv_status
  loop: "{{lsblk_out.stdout_lines}}"

- name: Update hosts freedisk list
  set_fact:
    host_disk: "{{host_disk + [item.item]}}"
  ignore_errors: true
  when: item.rc == 0
  loop: "{{ pv_status.results}}"

- name: RESULTS
  debug:
    var: host_disk

- name: Pre-condition disks Loop
  include: clean-disks.yaml
  with_sequence: count={{ dd_loop_count }}

- name: copy script..
  template:
    src: "clean-disks.j2"
    dest: "/tmp/clean-disks.sh"

- name: fix perms..
  file:
    path: /tmp/clean-disks.sh
    mode: 0755

- name: Pre-condition disks Loop
  include: clean-disks.yaml
  with_sequence: count={{ dd_loop_count }}

- name: Execute dd script
  shell:
    "/tmp/clean-disks.sh {{ host_disk | to_yaml }}"
  register: dd_async
  async: 3600
  poll:  0

- name: Check on background job
  async_status:
    jid: "{{ dd_async.ansible_job_id }}"
  register: dd_async_job_result
  until: dd_async_job_result.finished
  retries: 100
  delay: 10

- name: Delete test script
  file:
    path: /tmp/clean-disks.sh
    state: absent

