---
# tasks file for clean-disks

- name: setup
  set_fact:
    host_disk: []

- name: Get a list of block devices (excludes loop and child devices)
  command: lsblk -n --output NAME --nodeps --exclude 7
  register: lsblk_out

- name: check if disk {{ item }} is free
  command: pvcreate --test /dev/{{ item }}
  ignore_errors: true
  register: pv_status
  loop: "{{lsblk_out.stdout_lines}}"

- name: Update hosts freedisk list
  set_fact:
    host_disk: "{{host_disk + [item.item]}}"
  ignore_errors: true
  when: item.rc == 0
  loop: "{{ pv_status.results}}"

- name: RESULTS
  debug:
    var: host_disk


- name: Pre-condition disks Loop
  include: clean-disks.yaml
  with_sequence: count={{ dd_loop_count }}

